# Generated by Django 4.0.3 on 2022-03-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_rentbook_reterneddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentbook',
            old_name='reterneddate',
            new_name='returneddate',
        ),
    ]
